export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_RESET = 'PRODUCT_RESET'

export const FILTER_PRODUCTS_BY_CATEGORY_REQUEST = 'FILTER_PRODUCTS_BY_CATEGORY_REQUEST'
export const FILTER_PRODUCTS_BY_CATEGORY_SUCCESS = 'FILTER_PRODUCTS_BY_CATEGORY_SUCCESS'
export const FILTER_PRODUCTS_BY_CATEGORY_FAIL = 'FILTER_PRODUCTS_BY_CATEGORY_FAIL'

export const SORT_PRODUCTS_REQUEST = 'SORT_PRODUCTS_REQUEST'
export const SORT_PRODUCTS_SUCCESS = 'SORT_PRODUCTS_SUCCESS'
export const SORT_PRODUCTS_FAIL = 'SORT_PRODUCTS_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST'
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS'
export const LIST_PRODUCTS_FAIL = 'LIST_PRODUCTS_FAIL'

export const SET_PRODUCTS_REQUEST = 'SET_PRODUCTS_REQUEST'
export const SET_PRODUCTS_SUCCESS = 'SET_PRODUCTS_SUCCESS'
export const SET_PRODUCTS_FAIL = 'SET_PRODUCTS_FAIL'